language: cpp
compiler: g++
git:
  submodules: false
cache:
- build/dependencies
- build/GLTF/dependencies
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
script: mkdir build && cd build && cmake .. && make
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    git config --global user.email "builds@travis-ci.com";
    git config --global user.name "Travis CI";
    git tag -f -a latest -m "Live build of latest master from CI";
    git push --quiet https://${GH_TOKEN}@github.com/KhronosGroup/COLLADA2GLTF -f --tags > /dev/null 2>&1;
  fi;
- if [ ! -z "$TRAVIS_TAG" ]; then
    export RELEASE=`echo "$TRAVIS_TAG"| awk -F"-" '{print $1}'`;
    export RELEASE_FILE=COLLADA2GLTF-$RELEASE-linux.zip;
    find . -path ./CMakeFiles -prune -o -iname \*.a -o -perm /u+x | zip -@ -j $RELEASE_FILE;
  fi;
env:
  global:
  - secure: Ijvu7cYWehWEiNRJOrvsPUm21d+Hxk5G2pXiXPplBrpULgQIDKmaTlyfo/MkAAuL4yCXfbxVc4/u5LrnNrijWESpFMjTWD19WJRBwhkSpeYFujvKgCNBPi/DFzh7tN4fEjm+xwbTN4QXXBwHu/mr/zsTw3vjwVVhp7dHHSpRfi5WrmTNQM1kwduXfcrReV8t29W0uqJ2f2IVybrcUXyyxhevOiAZtJKNjBFudyMP62EGWygmSAiA7NU2j7TSMnOjwUANa84FnWmVSL8XVcDuilWNX2NgmQwnlP0xMhUp1V8gH1KyPZ0zOiwvs/shKqZn1h8CWkDZdbXOqmmRNmNYyv4ylO+bVU72DFKBXlpWZ/sFnhKvMXhV8aSXnUvgK7Lg7BUW9gWAEDvqD4wI8l3ilz8vl2lSbRiB1BcTvuoenIwu8Pw1cIC03FfJO/kG3xuEPgwmPTDwKd90Lp62IK8/qz5E3yoVXW/kanNkrRFXt8uHx/nCW4rIP2AYeJxLS7bk1th+GPyJB2BO5DYHGrU+yPKs+MCb7IdWeA3RcKirW2xpELpQc80nojOHTvB0jxsWGVUHthFk2K9imrjouoDW5aTuO1KqNiUGAQLe9UucXh/1ABYk4rXUWBTCDelSHvUlSMW9Fsk6S6aULU+75zmSJpj8FNjXYom/eKfj0cITq3M=
deploy:
  provider: releases
  api-key:
    secure: AUoIy2ukzHAWBPfXejuhYTu1fe08pjBtB+SY0YfG+TkMbiiL1EvbkEQlrhNkeOcBZoreKAVGPbHtpIL/t/NUXuo1qAmN47H6daxigAuWVE15lvvx/W+6SZN3eFGRCZ5UpRMs3Vg+4ZM4dtruAc7hy7cia3HBSO/Y/g0P65Mx0/+s6de2S01UmVWpTbgPcO8zovvdggxsjr0yZJaDd2UmlQj2tBRYOmS9PYZ0c/PRb9xNcoLZaPnPnu7OwbPiQQvS8LTckgWGui1kj9X36/mruW3TpgEkvH9itMkXPE5FvzlsPcvo5KvDImeSP6y8i+u/lqT57LpTe5SxhZr7nlyh0cvXQjFSqPrljkeVXYwTg6Gt/61Su1pKmv38MT8lQd/+EQpo614iEPMK5E/cXTgKeI3ZmMQI/9uMFZSMwDN6GOAlSmSxuXaI4OcMW5xtAbigyxTdsyk5+5vGmyOhTKvaGBH4E6Boaa8ZyAqCGE6Rfi6TgzbQoVue4AUULOGhLHXeXyCw9rKF9VwI867ZdXccbMvz3BD3CRFVJ/a0w2LgKNNyrA6eOE2hWloKFALkQBAiwuUV6S/rPeJq1msohpPXMlwdkRSj6qPWlMBFXWbLHPeADkTIf8Ysn7NxNJ+vpAbQWs4vs9kYVNoaEcNBtzIRtwk563aI1pXpKjDgzoFCtrk=
  file: $RELEASE_FILE
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
