version: 2.0.{build}
max_jobs: 1
image: Visual Studio 2015
matrix:
  fast_finish: true
  allow_failures:
  - platform: x86
    configuration: Debug
  - platform: x64
    configuration: Debug
  - platform: x86
    configuration: Release
  - platform: x64
    configuration: Release

platform:
- Win32
- x64

configuration:
- Debug
- Release

cache:
- dependencies -> .gitmodules
- GLTF/dependencies -> .gitmodules
- cmake-build/dependencies -> .gitmodules
- cmake-build/GLTF/dependencies -> .gitmodules

install:
- copy .gitmodules .gitmodules.bak
- powershell -Command "(gc .gitmodules) -replace 'git@github.com:', 'https://github.com/' | Out-File .gitmodules" -encoding UTF8
- git submodule update --init --recursive
# Make sure that gitmodules stays unchanged so that caching works
- copy /Y .gitmodules.bak .gitmodules

before_build:
- mkdir -p cmake-build
- cd cmake-build
- IF "%PLATFORM%"=="Win32" cmake -G "Visual Studio 14 2015" .. -Dtest=ON
- IF "%PLATFORM%"=="x64" cmake -G "Visual Studio 14 2015 Win64" .. -Dtest=ON

build:
  parallel: true
  project: cmake-build/COLLADA2GLTF.sln

after_build:
- 7z a COLLADA2GLTF-windows-"%CONFIGURATION%"-"%PLATFORM%".zip
  .\"%CONFIGURATION%"\COLLADA2GLTF-bin.exe
  .\"%CONFIGURATION%"\COLLADA2GLTF.lib
  .\GLTF\"%CONFIGURATION%"\GLTF.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\"%CONFIGURATION%"\COLLADASaxFrameworkLoader.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\COLLADAFramework\"%CONFIGURATION%"\COLLADAFramework.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\COLLADAFramework\COLLADABaseUtils\"%CONFIGURATION%"\COLLADABaseUtils.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\COLLADAFramework\COLLADABaseUtils\pcre\"%CONFIGURATION%"\pcre.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\COLLADAFramework\MathMLSolver\"%CONFIGURATION%"\MathMLSolver.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\GeneratedSaxParser\"%CONFIGURATION%"\GeneratedSaxParser.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\GeneratedSaxParser\expat\"%CONFIGURATION%"\expat.lib
  .\dependencies\OpenCOLLADA\modules\COLLADASaxFrameworkLoader\GeneratedSaxParser\LibXML\"%CONFIGURATION%"\LibXML.lib
  .\dependencies\argparse\modules\argparse\"%CONFIGURATION%"\argparse.lib

test_script:
- "%CONFIGURATION%\\COLLADA2GLTF-test.exe"
- "GLTF\\%CONFIGURATION%\\GLTF-test.exe"

artifacts:
- path: cmake-build/COLLADA2GLTF-windows-$(configuration)-$(platform).zip
  name: built-zip

deploy:
  description: Live build of latest master from CI
  provider: GitHub
  auth_token:
    secure: Nh+ZPhrI2P9EmI/+YlHiY7Roj/4dYHM0XMXr8rFX6O8q9mujEMbBNdbLw0QZ5Nq7
  on:
    appveyor_repo_tag: true
  force_update: true
